### ISSUE TITLE
Can Energy be set to Zero in software?

### ISSUE THREAD

**Issue by pieman64** [olehs/PZEM004T#23]
I know the Energy can be set to zero with the key in the LCD display or pressing the reset button on the board but I wondered if there was also a software hack?

If the Pzem is used for remote monitoring there will be nobody around to reset the Energy when each electric bill arrives and is validated as OK.

I have sent a message to Peacefair but just wondered of anyone had found a hack?

**Comment by pieman64** [comment]
Peacefair have replied and said there is no software hack to reset Energy, shame.

**Comment by vortigont** [comment]
I think this could be done with a help of one more optocoupler connected to the button and any mcu pin controlled via software.

**Comment by olehs** [comment]
@pieman64 I guess we can close the issue?

**Comment by pieman64** [comment]
Yes @olehs ok to close.
