### ISSUE TITLE
multiple PZEM004T's

### ISSUE THREAD

**Issue by phamiltonsmith** [olehs/PZEM004T#25]
Can I run/define multiple PZEM004T in one same code?

I would like to define 5 on one same unit...

TIA

**Comment by olehs** [comment]
Yes, if you have enough Hardware Serial ports and/or pins, suitable for Software Serial.
See also https://github.com/olehs/PZEM004T/issues/25

**Comment by phamiltonsmith** [comment]
I did not see issue #10....

I am in the process of building a meter (Arduino mega based) to read consumption on 3 phases and solar production on two phases...

Tks for the work y have put into this!
