### ISSUE TITLE
Hardware serial (ESP8266) Example

### ISSUE THREAD

**Issue by DimChik2903** [olehs/PZEM004T#26]
I can not figure out how to write a sketch to work with the hardware serial (RX/TX pin) on ESP8266. Could you add an example? Thank you in advance!

**Comment by vortigont** [comment]
@DimChik2903 
Something like this would do

```
HardwareSerial hwser(UART0);
PZEM004T pzem(&hwser); // Connect to PZEM via HW_serial
hwser.swap();                      // (optional) swap hw_serial pins to gpio13(rx),15(tx)
```

**Comment by hnaeem07** [comment]
Thanks a lot, it works.
