### ISSUE TITLE
can not buil for nodeMCU

### ISSUE THREAD

**Issue by hanguyen92205** [olehs/PZEM004T#28]
I used arduino IDE 1.8.5 & library esp8266 v2.3.0 for buil example with nodeMCU 1.0
![image](https://user-images.githubusercontent.com/13514363/32368561-ad1fca06-c0b8-11e7-986f-0616ccb3e8b9.png)
After that, i try rebuild example with Arduino IDE 1.6.6, but the same result
![image](https://user-images.githubusercontent.com/13514363/32368641-03c93108-c0b9-11e7-9a7b-8cce9f42fc1c.png)

**Comment by olehs** [comment]
see #14
