### ISSUE TITLE
Error compiling 

### ISSUE THREAD

**Issue by ayasystems** [olehs/PZEM004T#29]
Hi

I have an error when i try to compile your code.

I'm ussing Arduino Ide 1.8.1
ESP Library 2.3.0

Here the error:

C:\Users\Angel\AppData\Local\Temp\arduino_build_805687\sketch\PZEM004T.cpp: In member function 'bool PZEM004T::recieve(uint8_t, uint8_t*)':

C:\Users\Angel\AppData\Local\Temp\arduino_build_805687\sketch\PZEM004T.cpp:137:37: error: 'class SoftwareSerial' has no member named 'listen'

         ((SoftwareSerial *)serial)->listen();

What version of software serial are you using?

**Comment by olehs** [comment]
see #14
