### ISSUE TITLE
Won't work with ethernet shield

### ISSUE THREAD

**Issue by iFEARR** [olehs/PZEM004T#32]
I'm trying to hook up my pzem004t with my arduino mega with ethernet shield, but I can't use pins 10,11. And doesn't want to work with other pins. Any thoughts ?

**Comment by olehs** [comment]
I have a project with Mega and Ethernet. Works great on pins 11,12
`PZEM004T pzem(11, 12); // RX,TX`

**Comment by iFEARR** [comment]
Nice thanks! Now it's working. But when I try to read the values, it takes a long time, is that normal ?

**Comment by olehs** [comment]
PZEM allows to read max 2 values at once (per second). So if you try to read all 4 values - it will take minimum 2 seconds (if I remember it right).
