### ISSUE TITLE
esp8266 2.4.1 problem

### ISSUE THREAD

**Issue by xsiriusx** [olehs/PZEM004T#36]
using the library esp8266 2.4.1 the pzem004t probe does not read the watt and watt / h values. Restoring the library to 2.3.0 works great. Problem of library esp8266 or this library? sorry for my english

**Comment by xsiriusx** [comment]
just for information the problem is that randomly some readings are -1, as if communication was missing through the serial

**Comment by olehs** [comment]
Sorry, I can't check this setup right now (don't have this hardware). Maybe someone who has ESP and PZEM can check it.
But since the problem is random, I have to ask if you're testing it on default sample sketch? Did you change timeout setting in it?

**Comment by vortigont** [comment]
esp8266 2.4 core introduced a lot of changes that affects timing-dependent code. SoftwareSerial lib has some issues too (plerup/espsoftwareserial#63). You can try building with most recent SoftwareSerial lib code from git or use esp8266 with hardware-serial. I'm running it without any issues with a 2.4 core and SDK:2.2.1 in hwserial mode.
