### ISSUE TITLE
Delay

### ISSUE THREAD

**Issue by 303055** [olehs/PZEM004T#49]
Hi olehs,

Why is there 2 seconds delay between receiving information? Can it shorten?
Thx

**Comment by olehs** [comment]
No, it's hardware issue.

**Comment by olehs** [comment]
You can shorten delay between readings with setReadTimeout, but this will cause reading errors (-1.0)

**Comment by 303055** [comment]
Hello olehs,
Thank you for your quick reply !

So like this:

void setup () {
   Serial.begin (9600);
   pzem.setAddress (ip);
   pzem.setReadTimeout (1000); // 1000ms
}

Thx

**Comment by olehs** [comment]
1000ms is the default timout. You have to decrease it.
PZEM returns 2 readings in 1 second.

**Comment by 303055** [comment]
Thx olehs 
work fine for me

@+

**Comment by 303055** [comment]
thx olehs

work fine for me

@+
