### ISSUE TITLE
Does this work with the updated version of PZEM-004T

### ISSUE THREAD

**Issue by BrendenCA** [olehs/PZEM004T#58]
Hi,

There is a newer version of the PZEM-004T
It uses the Modbus–RTU, will this library work for it?

https://www.aliexpress.com/store/product/PZEM-004T-Update-Version-AC-Single-Phase-Multifunction-Ampere-Meter-Watt-Power-Volt-Amp-Kwh-TTL/1773456_32907139707.html?spm=2114.12010612.8148356.2.a5605ff1fOKeWd

Thanks,

**Comment by Giardo84** [comment]
> Hi,
> 
> There is a newer version of the PZEM-004T
> It uses the Modbus–RTU, will this library work for it?
> 
> https://www.aliexpress.com/store/product/PZEM-004T-Update-Version-AC-Single-Phase-Multifunction-Ampere-Meter-Watt-Power-Volt-Amp-Kwh-TTL/1773456_32907139707.html?spm=2114.12010612.8148356.2.a5605ff1fOKeWd
> 
> Thanks,

I've tried but it doesn't work

**Comment by schreda** [comment]
Is there a working library out there already?

**Comment by SeByDocKy** [comment]
Desperatly need a V3 support :( :( :( :( .....

**Comment by xcusso** [comment]
+1

**Comment by xcusso** [comment]
The new n version is working with pzem-016, but I don't know why..

**Comment by SumeriLal** [comment]
Use this library: https://github.com/SumeriLal/Arduino/tree/master/MasterPZEM

**Comment by mandulaj** [comment]
Hi, a bit late, but here is another one too :smile: 
https://github.com/mandulaj/PZEM-004T-v30
