### ISSUE TITLE
PZEM-004 vs PZEM-004T

### ISSUE THREAD

**Issue by ipa64** [olehs/PZEM004T#67]
Hi,
I have these two versions with their documentations.
At first I thought they are the same, 004 has display 7seg, 004T doesn’t have display.
But it’s wrong, the protocol between 004 and 004T is different, 004T I use Modbus-RTU
And the protocol you describe in your readme match to the PZEM-004.
So your library should be named PZEM-004
Or maybe they have changed the protocol without modify the name, I hope not ???
There is on internet a lot of confusion with this two modules.

**Comment by olehs** [comment]
Hi, I guess they change versions as they want (
The library was written for the board like on the image below. It says "V1.0" - maybe that's the key.
![image](https://user-images.githubusercontent.com/606709/101462323-c7592680-3944-11eb-97dc-e47f586934b4.png)

**Comment by ipa64** [comment]
I just got information from Peacefair 
From 004T v3.0 protocol is Modbus-RTU, previous version was not !
So they changed the protocol without modifying the name ! So bad!

**Comment by ipa64** [comment]
And the icing on the cake:
PZEM-004 v3.0 with display doesn’t  have Modbus-RTU protocol !
