### ISSUE TITLE
PZEM-004v3.0 address not set by default to 192.168.1.1

### ISSUE THREAD

**Issue by ipa64** [olehs/PZEM004T#68]
Hi,
I have got 3 PZEM-004v3.0, they use the old protocol ( before modebus-rtu ) they was not working on 
Tasmota 9.1.0
Tx PZEM0XX TX
RX PZEM004 RX

Using CoolTerm I set manually the address to 192.168.1.1 ( B4 C0 A8 01 01 00 1E )
After that they was all of them working with Tasmota 

So:
Is the driver setting an address on init ?
Is there a way on Tasmota to set the module address ?
Thank you

**Comment by olehs** [comment]
You have to call method `pzem.setAddress` on initialization to set it address. See examples
