### ISSUE TITLE
use mega hardware serial

### ISSUE THREAD

**Issue by th4904** [olehs/PZEM004T#7]
I want use arduino mega and two pzem sensors.
but two software serial is not work well.
how to use mega`s hardware serial?

**Comment by olehs** [comment]
You're right. We need to add some flexibility to support combinations of software/hardware ports on different controllers.
I'll see what I can do.

**Comment by olehs** [comment]
Added ability to use different Hardware Serial ports. See examples

**Comment by th4904** [comment]
thanks to update.
but hardware serial example is not run.
plz check your lib

**Comment by olehs** [comment]
What controller do you use?

**Comment by th4904** [comment]
use arduino mega 2560 
![image](https://cloud.githubusercontent.com/assets/22461650/19264912/d47eae4e-8fdd-11e6-9757-bfa5e9045866.png)

**Comment by th4904** [comment]
thank!!
new lib is work!!
