### ISSUE TITLE
Problem on ESP8266ex

### ISSUE THREAD

**Issue by bizteco0** [olehs/PZEM004T#8]
I uploaded PZEMDisplay.ino to WeMos D1 R2 Mini which based on esp8266ex.
But i faced the below error.
14.90V; 0.00A; 0.00W; 8.00Wh; 
215.00V; 0.00A; 0.00W; 8.00Wh; 
214.80V; 0.00A; 0.00W; 8.00Wh; 
214.90V; 0.00A; 
Soft WDT reset

ctx: cont 
sp: 3ffef410 end: 3ffef680 offset: 01b0

>>>stack>>>
3ffef5c0:  feefef00 feefeffe feefeffe 3ffef607  
3ffef5d0:  3fff04d4 00000006 3ffee478 40202115  
3ffef5e0:  3ffe84c0 00000002 3ffe842e 3ffee478  
3ffef5f0:  000000a2 00000000 3ffee478 402020a2  
3ffef600:  01a8c0b2 001c0001 3ffee59c 3ffee478  
3ffef610:  3ffee470 00000000 3ffee478 402022a1  
3ffef620:  3ffee470 00000000 3ffee59c 402025f4  
3ffef630:  01a8c0b4 00000000 3ffee59c 40201cbf  
3ffef640:  00000000 00000000 3ffee478 40202335  
3ffef650:  00000000 00000000 00000001 3ffee658  
3ffef660:  3fffdad0 00000000 3ffee650 40202c4c  
3ffef670:  feefeffe feefeffe 3ffee660 40100718  
<<<stack<<<

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v09f0c112
~ld
?214.90V; 0.00A; 0.00W; 8.00Wh; 
214.90V; 0.00A; 0.00W; 8.00Wh; 
214.60V; 0.00A; 0.00W; 8.00Wh; 
214.70V; 0.00A; 0.00W; 8.00Wh; 
214.90V; 0.00A; 
....

i tried to find why occurred it. first so i commented  
  // float p = pzem.power(ip);
  // if(p >= 0.0){ Serial.print(p);Serial.print("W; "); }
and uploaded it. i met with the below 
=====================
215.00V; 0.00A; 8.00Wh; 
215.10V; 0.00A; 8.00Wh; 
215.00V; 0.00A; 8.00Wh; 
214.90V; 0.00A; 8.00Wh; 
215.00V; 0.00A; 8.00Wh; 
215.10V; 0.00A; 8.00Wh; 
214.50V; 0.00A; 8.00Wh; 
215.10V; 0.00A; 8.00Wh; 
215.00V; 0.00A; 8.00Wh; 
214.80V; 0.00A; 8.00Wh; 
214.20V; 0.00A; 8.00Wh; 
215.00V; 0.00A; 8.00Wh; 
215.20V; 0.00A; 8.00Wh; 
215.10V; 0.00A; 
Soft WDT reset

ctx: cont 
sp: 3ffef410 end: 3ffef680 offset: 01b0

>>>stack>>>
3ffef5c0:  feefef00 feefeffe feefeffe 3ffef607  
3ffef5d0:  3fff04d4 00000006 3ffee478 402020dd  
3ffef5e0:  3ffe84b8 00000002 3ffe842e 3ffee478  
3ffef5f0:  000000a3 00000000 3ffee478 4020206a  
3ffef600:  01a8c0b3 001d0001 3ffee59c 3ffee478  
3ffef610:  3ffee470 00000000 3ffee478 40202269  
3ffef620:  3ffee470 00000000 3ffee59c 40202574  
3ffef630:  01a8c0b4 00000000 3ffee59c 40201cbb  
3ffef640:  00000000 00000000 3ffee478 402022b5  
3ffef650:  00000000 00000000 00000001 3ffee658  
3ffef660:  3fffdad0 00000000 3ffee650 40202bcc  
3ffef670:  feefeffe feefeffe 3ffee660 40100718  
<<<stack<<<

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v09f0c112
~ld
?214.10V; 0.00A; 8.00Wh; 
214.80V; 0.00A; 8.00Wh; 
215.10V; 0.00A; 
Soft WDT reset

ctx: cont 
sp: 3ffef420 end: 3ffef680 offset: 01b0

>>>stack>>>
3ffef5d0:  3fff04d4 00000006 3ffee478 402020dd  
3ffef5e0:  3ffe84b8 00000002 3ffe842e 3ffee478  
3ffef5f0:  000000a3 00000000 3ffee478 4020206a  
3ffef600:  01a8c0b3 001d0001 3ffee59c 3ffee478  
3ffef610:  3ffee470 00000000 3ffee478 40202269  
3ffef620:  3ffee470 00000000 3ffee59c 40202574  
3ffef630:  01a8c0b4 00000000 3ffee59c 40201cbb  
3ffef640:  00000000 00000000 3ffee478 402022b5  
3ffef650:  00000000 00000000 00000001 3ffee658  
3ffef660:  3fffdad0 00000000 3ffee650 40202bcc  
3ffef670:  feefeffe feefeffe 3ffee660 40100718  
<<<stack<<<

I found that it occurred  when read the Power and Energy.

Let me know why.

**Comment by olehs** [comment]
Try adding wdt_reset() after each call to library functions. Or you can disable or increase WDT.
