### ISSUE TITLE
ESP8266

### ISSUE THREAD

**Issue by tmckc44** [olehs/PZEM004T#9]
Sorry, I want to connect the PZEM004T with ESP8266  but,it have the problem. It can't read the voltage or anything please you tell me  how to connect this 2 module pls.

**Comment by iPAS** [comment]
At least 2-TODO things need to be done before the energy could be request from PZEM004T:
1) Connect 5V-VCC to UART port, the 3.3V is not enough, 
2) Set the address via command through UART interface before any other request following.
